### DISCUSSION TITLE
Use twist topic

### DISCUSSION THREAD

**Discussion by lidiaxp** [ctu-mrs/mrs_uav_system#131] [General]
I would like to perform some tests in your but without using the pre-defined controls. Is it possible to use the topic "/control_manager/cmd_twist_out", that is a ? If yes, how can I release it? Because when I send a command to it by rostopic pub, the UAV does not make any movement.

Thank you in advance

**Comment by klaxalk** [comment]
Hey, the supported topics and services are listed here: https://ctu-mrs.github.io/docs/system/uav_ros_interface.html. The mentioned `cmd_twist_out` is being published by the control manager just to report on the current velocity reference.

Use the `control_manager/velocity_reference` topic if you want velocity control. However, many of our control layers will still be active, in this case, the SO(3), SE(3) feedback, and the MpcTracker reference generator.

**Reply by lidiaxp** [reply]
I tried:

```
rostopic pub /uav1/control_manager/velocity_reference mrs_msgs/VelocityReferenceStamped "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
reference:
  velocity: {x: 10.0, y: 0.0, z: 0.0}
  altitude: 0.0
  heading: 0.0
  heading_rate: 0.0
  use_altitude: false
  use_heading: false
  use_heading_rate: false"
```

But the UAV just movement a few centimeters. There are a topic similar to ```cmd_vel``` which we send a value and UAV still movement until we send 0? Or I am using the topic ```control_manager/velocity_reference``` in a wrong way?
