### DISCUSSION TITLE
How to overwrite the constraints

### DISCUSSION THREAD

**Discussion by lidiaxp** [ctu-mrs/mrs_uav_system#174] [Q&A] [answered]
I am trying to use the `fast` mode, but I am not able to overwrite the default constraints configurations (after take off), it is using the `medium` mode: 

```
horizontal_speed: 4.0
horizontal_acceleration: 2.0
horizontal_jerk: 40.0
horizontal_snap: 40.0
vertical_ascending_speed: 2.0
vertical_ascending_acceleration: 1.0
vertical_ascending_jerk: 40.0
vertical_ascending_snap: 40.0
vertical_descending_speed: 2.0
vertical_descending_acceleration: 1.0
vertical_descending_jerk: 40.0
vertical_descending_snap: 40.0
heading_speed: 1.0
heading_acceleration: 1.0
heading_jerk: 20.0
heading_snap: 20.0
roll_rate: 60.0
pitch_rate: 60.0
yaw_rate: 10.0
tilt: 1.0471975511965976
```
I am trying to modify it in the config files, more specific in the `custom_config.yaml`, with this file:
```
mrs_uav_managers:
  estimation_manager:
    state_estimators: [
      "gps_baro",
    ]

    initial_state_estimator: "gps_baro" 
    agl_height_estimator: "" 

  uav_manager:

    takeoff:

      after_takeoff:
        controller: "MpcController"
        constraints: "fast"

      takeoff_height: 10.0

      constraint_management:

        fallback_constraints:
      
            gps_baro: "fast"

mrs_uav_trajectory_generation:

  max_time: 0.5 # [s]

  check_trajectory_deviation:
    max_deviation: 0.20 # [m]

  path_straightener:
    enabled: true
    max_deviation: 0.20 # [m]
```

But, in the simulation, the topic `/uav1/control_manager/current_constraints` shows the medium constraints. I am doing these tests in `mrs_octomap_mapping_planning` example with default values in the other config files. How could I modify these constraints to use the `fast` one? Or even a customized constraint?

Thank you very much for your help

**Comment by klaxalk** [comment]
Hey Lidia, the "constraint_management" block does not go under the "uav_manager", but "constraint_manager". So

```yaml

mrs_uav_managers:

  constraint_manager:

    default_constraints:
      gps_garmin: "slow"
      gps_baro: "slow"

```
