### DISCUSSION TITLE
How to turn on RTK in Gazebo simulation?

### DISCUSSION THREAD

**Discussion by maxhofidrone** [ctu-mrs/mrs_uav_system#179] [Q&A] [answered]
Hi,
I want to turn on the RTK within the gazebo simulation. with the pre-1.5 version I always exported the tag `export ODOMETRY_TYPE="rtk"`. As I understand the config-file handling in the version 1.5 this should not be necessary anymore right?
When starting following `session.yaml` in the mrs_multirotor_simulator configuration (commented out currently), everything works as expected. In the Gazebo configuration `core` is throwing errors for missing RTK messages. Can you please give me any hints for turning on RTK messages in Gazebo?
```
# do not modify these
root: ./
name: simulation
socket_name: mrs
attach: false
tmux_options: -f /etc/ctu-mrs/tmux.conf
# you can modify these
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=x500
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
#  - simulator:
#      layout: tiled
#      panes:
#        - waitForRos; roslaunch mrs_multirotor_simulator multirotor_simulator.launch custom_config:=./config/simulator.yaml
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_uav_gazebo_simulation simulation.launch world_name:=grass_plane gui:=true
        - waitForGazebo; rosservice call /mrs_drone_spawner/spawn "1 --$UAV_TYPE --enable-rangefinder"
        - waitForControl; gz camera -c gzclient_camera -f $UAV_NAME; history -s gz camera -c gzclient_camera -f $UAV_NAME
  - status:
      layout: tiled
      panes:
        - waitForHw; roslaunch mrs_uav_status status.launch 
  - hw_api:
      layout: tiled
      panes:
        - waitForTime; roslaunch mrs_uav_px4_api api.launch
#  - hw_api:
#      layout: tiled
#      panes:
#        - waitForTime; roslaunch mrs_multirotor_simulator hw_api.launch custom_config:=./config/hw_api.yaml
  - core:
      layout: tiled
      panes:
        - waitForHw; roslaunch mrs_uav_core core.launch
          platform_config:=`rospack find mrs_uav_gazebo_simulation`/config/mrs_uav_system/$UAV_TYPE.yaml
          custom_config:=./config/custom_config.yaml
          world_config:=./config/world_config.yaml
          network_config:=./config/network_config.yaml
  - takeoff:
      layout: tiled
      panes:
        - waitForHw; roslaunch mrs_uav_autostart automatic_start.launch
        - 'waitForControl; rosservice call /$UAV_NAME/hw_api/arming 1; sleep 2; rosservice call /$UAV_NAME/hw_api/offboard'
  - goto:
      layout: tiled
      panes:
        - 'history -s rosservice call /$UAV_NAME/control_manager/goto \"goal: \[0.0, 10.0, 1.5, 0.0\]\"'
  - emulation:
      layout: tiled
      panes:
        - waitForControl; roslaunch emulated_sensors emulation.launch
  - rviz:
      layout: tiled
      panes:
        - waitForControl; roslaunch mrs_uav_core rviz.launch
        - waitForControl; roslaunch mrs_rviz_plugins load_robot.launch
        - waitForControl; roslaunch mrs_rviz_plugins rviz_interface.launch
  - layout:
      layout: tiled
      panes:
        - waitForControl; sleep 3; ~/.i3/layout_manager.sh ./layout.json
```

my `custom_config.yaml`:
```
mrs_uav_managers:

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "rtk",
    ]

    initial_state_estimator: "rtk" # will be used as the first state estimator
    agl_height_estimator: "garmin_agl" # only slightly filtered height for checking min height (not used in control feedback)

  uav_manager:
    # periodically checks if max height was exceeded
    # if so, retakes control and descends below it
    max_height_checking:

      enabled: false
      rate: 10.0 # [Hz]
      safety_height_offset: 0.25 # how much lower to descend below the max height

    # periodically checks if min height was exceeded
    # if so, retakes control and ascends above it
    min_height_checking:

      enabled: false
      rate: 10.0 # [Hz]
      min_height: 0.5 # [m]
      safety_height_offset: 0.25 # how much higher to ascend above the min height

    takeoff:

      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "MpcController" # more robust
        # controller: "Se3Controller" # more precise
        tracker: "MpcTracker"

mrs_uav_trajectory_generation:

  # execution time limiter
  max_time: 10 # [s]

  # when true, only the fallback solver will be used by default
  enforce_fallback_solver: false

  # check and fix the max deviation between the input path and the output trajectory
  # by subsampling the original path with more waypoints
  check_trajectory_deviation:
    enabled: true
    max_deviation: 1.0 # [m]
    max_iterations: 3 # [-]
```
