### DISCUSSION TITLE
Use ALOAM and Octomap in simulation

### DISCUSSION THREAD

**Discussion by lidiaxp** [ctu-mrs/mrs_uav_system#184] [General]
I am trying to use ALOAM as the estimator and octomap for mapping the environment.

In session.yml, I added:
```
- slam:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_aloam_core slam_pipeline.launch OUSTER_TYPE:=OS0-128
  - mapplan:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_octomap_mapping_planning mapplan.launch
          config_octomap_server:=./config/octomap_server.yaml
          config_octomap_planner:=./config/octomap_planner.yaml
          config_pcl_filter_ouster:=./config/ouster_filter_mapping.yaml
          config_pcl_filter_rs_front:=./config/rs_front_filter.yaml
          config_pcl_filter_rs_down:=./config/rs_down_filter.yaml
```
It works perfectly with gps_baro as the estimator; I can see the map from slam and octomap. However, when I change the custom configuration to use ALOAM as the estimator:

`custom_config:=rospack find mrs_aloam_estimator_plugin/custom_configs/mrs_uav_managers.yaml`

I cannot see the map generated from octomap anymore.

This is my default custom_config where ALOAM and octomap seem to be working:
```
mrs_uav_managers:

  constraint_manager:
    default_constraints:
        gps_garmin: "fast"
        gps_baro: "fast"

  estimation_manager:

    # loaded state estimator plugins
    state_estimators: [
      "gps_garmin",
      "gps_baro",
    ]

    initial_state_estimator: "gps_baro" 
    agl_height_estimator: "garmin_agl"

  uav_manager:

    takeoff:
      during_takeoff:
        controller: "MpcController"
        tracker: "LandoffTracker"

      after_takeoff:
        controller: "MpcController"
        tracker: "MpcTracker"
```

II could not identify what could be wrong since only the estimator is being modified. Do you know what could be wrong? I am trying to do it in the simulation.

I am using these sensors in the simulation:
`
waitForGazebo; rosservice call /mrs_drone_spawner/spawn "1 $UAV_TYPE --enable-realsense-front --enable-rangefinder --use-gpu-ray --enable-ground-truth --enable-ouster model:=OS0-128 horizontal_samples:=1024 use_gpu:=True --pos -5 0 0 0"`

The topic I am checking for the octomap is /uav1/octomap_global_vis/occupied_cells_vis_array.
