### DISCUSSION TITLE
open_vins with RealSense depth camera: Error: "failed static init: no accel jerk detected, platform moving too much"

### DISCUSSION THREAD

**Discussion by MJavadZallaghi** [ctu-mrs/mrs_uav_system#203] [Q&A]
I have a simulation for T650 robot with an enabled RealSense stereo camera in front of the robot. I want to use [mrs_open_vins_core](https://github.com/ctu-mrs/mrs_open_vins_core) as state estimator. When running this simulation, I have this warning in in open_vins tab:
```bash
...
[init]: disparity is 12.728,11.495 (10.00 thresh)
[init]: failed static init: no accel jerk detected, platform moving too much
[TIME]: 0.0195 seconds total (51.3 hz, 0.55 ms behind)
...
```
So visual odometery of [mrs_open_vins_core](https://github.com/ctu-mrs/mrs_open_vins_core) doesn't work based on this terminal log. 

Is there any hint on the issue? For providing more data, in the following you can find some Screenshots and source codes for my simulation tmux yaml file and launch files for RealSense sensor and open_vins.

Thanks in advance foy your help!

Visual tracking features during takeoff:
![image](https://github.com/user-attachments/assets/bc338e1c-6352-45a2-a496-f66c7c0de937)

Visual tracking features after takeoff:
![image](https://github.com/user-attachments/assets/fcec7f31-856f-4177-8b4e-af064d687d18)

Screenshot of my open_vins tab from the terminal:
![image](https://github.com/user-attachments/assets/97fda22f-bbb5-48a5-bc1b-edf8753e804b)

My tmux yaml:
```yaml
root: ./
name: simulation
socket_name: mrs
attach: false
tmux_options: -f /etc/ctu-mrs/tmux.conf
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=t650; export SENSORS="" # {garmin_down, garmin_up, rplidar, realsense_front, teraranger, bluefox_optflow, realsense_brick, bluefox_brick}
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_uav_gazebo_simulation simulation.launch world_name:=grass_plane gui:=true
        - waitForControl; gz camera -c gzclient_camera -f $UAV_NAME; history -s gz camera -c gzclient_camera -f $UAV_NAME
  - status:
      layout: tiled
      panes:
        - waitForHw; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: tiled
      panes:
        - waitForGazebo; rosservice call /mrs_drone_spawner/spawn "1 --$UAV_TYPE --pos 0 0 0 0 --enable-realsense-front --enable-rplidar --enable-rangefinder --enable-rangefinder-up"
  - hw_api:
      layout: tiled
      panes:
        - waitForTime; roslaunch mrs_uav_px4_api api.launch
  - core:
      layout: tiled
      panes:
        - waitForHw; roslaunch mrs_uav_core core.launch
          platform_config:=`rospack find mrs_uav_gazebo_simulation`/config/mrs_uav_system/$UAV_TYPE.yaml
          custom_config:=`rospack find mrs_open_vins_estimator_plugin`/custom_configs/mrs_uav_managers.yaml
          world_config:=./custom_configs/world_config.yaml
          network_config:=./custom_configs/network_config.yaml
  - open_vins:
      layout: tiled
      panes:
        - waitForHw; roslaunch brubotics_drone_sim simulation_realsense.launch 
  - vins_republisher:
      layout: tiled
      panes:
        - waitForHw; roslaunch brubotics_drone_sim vins_republisher_openvins_realsense.launch
  - change_odom_source:
      layout: tiled
      panes:
        -  waitForOffboard; sleep 10; rosservice call /$UAV_NAME/estimation_manager/change_estimator "open_vins"
  - takeoff:
      layout: tiled
      panes:
        - waitForHw; roslaunch mrs_uav_autostart automatic_start.launch
        - 'waitForControl; rosservice call /$UAV_NAME/hw_api/arming 1; sleep 2; rosservice call /$UAV_NAME/hw_api/offboard'
  - goto:
      layout: tiled
      panes:
        - 'history -s rosservice call /$UAV_NAME/control_manager/goto \"goal: \[0.0, 10.0, 1.5, 0.0\]\"'
  - rviz:
      layout: tiled
      panes:
        - waitForControl; roslaunch mrs_open_vins_core rviz.launch
        - waitForTime; waitForControl; roslaunch mrs_rviz_plugins rviz_interface.launch
  - layout:
      layout: tiled
      panes:
        - waitForControl; sleep 3; ~/.i3/layout_manager.sh ./layout.json
```

`simulation_realsense.launch` launch file of the sensor for mrs_open_vins_core:
```xml
<launch>

  <arg name="UAV_NAME" default="$(optenv UAV_NAME)" />

  <!-- what config we are going to run (should match folder name) -->
  <arg name="config"      default="rs_d455" /> <!-- euroc_mav, tum_vi, rpng_aruco -->
  <arg name="config_path" default="$(find brubotics_drone_sim)/config/mrs_open_vins_core/$(arg config)/estimator_config.yaml" />

  <!-- will it run using GNU debugger? -->
  <arg name="DEBUG" default="false" />
  <arg unless="$(arg DEBUG)" name="launch_prefix" value=""/>
  <arg     if="$(arg DEBUG)" name="launch_prefix" value="debug_roslaunch"/>

  <!-- will it run as standalone nodelet or using a nodelet manager? -->
  <arg name="standalone" default="true" />
  <arg name="manager" default="$(arg UAV_NAME)_vio_manager" />
  <arg name="n_threads" default="8" />
  <arg unless="$(arg standalone)" name="nodelet" value="load"/>
  <arg     if="$(arg standalone)" name="nodelet" value="standalone"/>
  <arg unless="$(arg standalone)" name="nodelet_manager" value="$(arg manager)"/>
  <arg     if="$(arg standalone)" name="nodelet_manager" value=""/>

  <group ns="$(arg UAV_NAME)">

    <group unless="$(arg standalone)">
      <node pkg="nodelet" type="nodelet" name="$(arg manager)" args="manager" output="screen" launch-prefix="$(arg launch_prefix) nice -n -10">
        <param name="num_worker_threads" value="$(arg n_threads)" />
      </node>
    </group>

    <!-- MASTER NODE! -->
    <node pkg="nodelet" type="nodelet" name="ov_msckf" args="$(arg nodelet) run_subscribe_msckf/RunSubscribeMsckf $(arg nodelet_manager)" launch-prefix="$(arg launch_prefix)" output="screen">

      <param name="uav_name"              type="string" value="$(arg UAV_NAME)" />

      <!-- master configuration object -->
      <param name="config_path"            type="string" value="$(arg config_path)" />

      <!-- topics -->
      <param name="topic_imu"      type="string" value="/$(arg UAV_NAME)/hw_api/imu" />
      <param name="topic_camera0"  type="string" value="/$(arg UAV_NAME)/rgbd/infra1/image_raw" />
      <param name="topic_camera1"  type="string" value="/$(arg UAV_NAME)/rgbd/infra2/image_raw" />

    </node>

  </group>

</launch>

```

`vins_republisher_openvins_realsense.launch` launch file of vins_republisher_openvins:
```xml
<launch>

  <arg name="UAV_NAME" default="$(optenv UAV_NAME uav1)"/>

  <arg name="camera_pitch" default="0.0"/>

  <arg name="mrs_vins_world_frame" default="$(arg UAV_NAME)/mrs_vins_world"/>
  <arg name="vins_world_frame" default="$(arg UAV_NAME)/ov_global"/>
  <arg name="fcu_frame" default="$(arg UAV_NAME)/fcu"/>
  <arg name="vins_fcu_frame" default="$(arg UAV_NAME)/ov_imu"/>
  <arg name="vins_fcu_front_frame" default="$(arg UAV_NAME)/vins_body_front"/>

  <!-- will it run using GNU debugger? -->
  <arg name="DEBUG" default="false" />
  <arg unless="$(arg DEBUG)" name="launch_prefix_debug" value=""/>
  <arg     if="$(arg DEBUG)" name="launch_prefix_debug" value="debug_roslaunch"/>

  <!-- nodelet settings-->
  <arg name="standalone" default="true" />
  <arg name="manager" default="$(arg UAV_NAME)_vinsrepublisher_manager" />
  <arg name="n_threads" default="8" />
  <arg unless="$(arg standalone)" name="nodelet" value="load"/>
  <arg     if="$(arg standalone)" name="nodelet" value="standalone"/>
  <arg unless="$(arg standalone)" name="nodelet_manager" value="$(arg manager)"/>
  <arg     if="$(arg standalone)" name="nodelet_manager" value=""/>

  <group ns="$(arg UAV_NAME)">

      <!-- ================= Static transformations ================= -->

    <!-- TF between the FCU of the UAV and the VINS body (IMU) frame -->
    <node pkg="tf2_ros" type="static_transform_publisher" name="tf_vins_fcu_to_mrs_fcu" args="0.085 0.0 0.13 1.5708 0.0 1.5708 $(arg fcu_frame) $(arg vins_fcu_front_frame)" />

    <!-- TF for variable pitch of the camera -->
    <node pkg="tf2_ros" type="static_transform_publisher" name="tf_vins_fcu_to_mrs_fcu2" args="0 0 0 0 0 $(arg camera_pitch) $(arg vins_fcu_front_frame) $(arg vins_fcu_frame)" />

      <!-- ================= VinsRepublisher nodelet ================ -->
    <node pkg="nodelet" type="nodelet" name="vins_republisher" args="$(arg nodelet) vins_republisher/VinsRepublisher $(arg nodelet_manager)" launch-prefix="$(arg launch_prefix_debug)" output="screen">

      <rosparam file="$(find brubotics_drone_sim)/config/mrs_vins_republisher/default.yaml" command="load" />

      <param name="uav_name" value="$(arg UAV_NAME)"/>

      <!-- set to true if velocity is defined in the IMU frame -->
      <param name="velocity_in_body_frame" value="true"/>

      <remap from="~vins_odom_in" to="ov_msckf/odomimu"/>
      <remap from="~vins_odom_out" to="~odom"/>

      <param name="fcu_frame" value="$(arg fcu_frame)"/>
      <param name="mrs_vins_world_frame" value="$(arg mrs_vins_world_frame)"/>
      <param name="vins_fcu_frame" value="$(arg vins_fcu_frame)"/>

    </node>
  </group>
</launch>

```

**Comment by petrlmat** [comment]
Hi, please use the provided [tmux session](https://github.com/ctu-mrs/mrs_open_vins_core/blob/master/ros_packages/mrs_open_vins_core/tmux/simulation/simulation.sh) for open_vins in gazebo simulation.

If you want to use a different sensor configuration, you need to specify the correct intrinsic and extrinsic parameters to open_vins and maybe also change the initialization parameters. Please refer to the open_vins documentation on how to do that.

**Reply by MJavadZallaghi** [reply]
Thank you @petrlmat

The simulation you mentioned uses a fisheye sensor with an integrated IMU `--enable-vio`  on f330 robot as vio sensor.
I want to perform vio in Gazebo simulation with realsense sensor `--enable-realsense-front` on t650. The first problem of this simulation is simulated realsense doesn't have integarted high-speed IMU, while vio sensor of the simulation script you provided has that IMU topic. Meanwhile, I'll ask open-vins community. 

Generally, is it possible to use another IMU source just for simulation for vio data input? If not, is it possible to add a highspeed IMU to realsense simulated sensor of mrs?

I have seen different configuration files here [https://github.com/ctu-mrs/mrs_open_vins_core/tree/master/ros_packages/mrs_open_vins_core/config](https://github.com/ctu-mrs/mrs_open_vins_core/tree/master/ros_packages/mrs_open_vins_core/config) for different sensors in mrs-open-vins-core repo:
![image](https://github.com/user-attachments/assets/8ac838ff-8466-4ff3-82f8-b6fec84d64f6)


Have you teested open-vins vio with these different sensors? Are the parameters configuration files there tested with real world robots? Can I use them as parameter references if I use the same sensors?

**Reply by migsdigs** [reply]
Hi @MJavadZallaghi 

I was wondering if you managed to make any further progress on this topic? I am also looking to experiment with open-vins using either OAK-D or Realsense depth camera. I would greatly appreciate you feedback.

Thanks!

**Reply by MJavadZallaghi** [reply]
Hi @migsdigs. Right now I'm calibrating a RealSense D455 for open-vins [following this tutorial](https://www.youtube.com/watch?v=rBT5O5TEOV4). This will give me yaml kalib calibration files needed by open-vins. I will post here my results after calibration and my experience with open-vins.

But noticed about another issue. If you install open-vins and calibration tools like allan_variance_ros and kalibr (which are needed in open-vins for doing hardware calibrations) in your ROS worksapce, then mrs-open-vins package won't work anymore! Indeed, there would be a conflict. At the moment I don't care about this issue, as it seems challenging for using mrs-open-vins in simulations as heavy sensor calibration is needed, and I don't have an idea how it can be done with mrs simulator!

So after D455 calibration with allan_variance_ros and kalibr, I will test open-vins with camera for odometery, If it worked fine then I'll use that sensor on my aerial robot with  mrs-open-vins, but with tested and calibrated yaml files I'm working on at the moment.

**Reply by migsdigs** [reply]
Hi @MJavadZallaghi !

Thank you very much for this, I really appreciate you getting back to me quickly. I look forward to hearing about your results and experience.

I am waiting on an OAK-D camera which I have ordered, afterwhich I will follows the same steps as you and try to have open-vins working with it (I think it will be slightly easier as a number of the necessary files for OAK-D already exist in MRS.

Cheers, 
Miguel

**Comment by MJavadZallaghi** [comment]
I finally used open-vins after performing imu-camera calibration of RealSense D455 using kalibr software on hardware. 6 DOF pos estimation is done very well. Still not used it from mrs-open-vins and used open-vins directly, but there would be no difference as the imu-camera calibration and the configure files are the same of open-vins that I have working at the moment. When I test mrs-open-vins, I can put an extra confirmation on this.

Image of 6 DOF pos estimation using open-vins
![image](https://github.com/user-attachments/assets/40bb80b6-134a-493f-8b4c-927dc74b1256)


This is the link to imu-camera calibration tutorial needed for open-vins: [https://www.youtube.com/watch?v=BtzmsuJemgI](https://www.youtube.com/watch?v=BtzmsuJemgI)

The **only open question** for me is still using mrs-open-vins **in mrs gazebo simulator**, as I don't know how to performation calibration needed for open-vins in a simulator! :)

For my D455, this is the open-vins `estimator_config.yaml`:

```yaml
%YAML:1.0 # need to specify the file type at the top!

verbosity: "INFO" # ALL, DEBUG, INFO, WARNING, ERROR, SILENT

use_fej: true # if first-estimate Jacobians should be used (enable for good consistency)
integration: "rk4" # discrete, rk4, analytical (if rk4 or analytical used then analytical covariance propagation is used)
use_stereo: true # if we have more than 1 camera, if we should try to track stereo constraints between pairs
max_cameras: 1 # how many cameras we have 1 = mono, 2 = stereo, >2 = binocular (all mono tracking)

calib_cam_extrinsics: true # if the transform between camera and IMU should be optimized R_ItoC, p_CinI
calib_cam_intrinsics: true # if camera intrinsics should be optimized (focal, center, distortion)
calib_cam_timeoffset: true # if timeoffset between camera and IMU should be optimized
calib_imu_intrinsics: true # if imu intrinsics should be calibrated (rotation and skew-scale matrix)
calib_imu_g_sensitivity: true # if gyroscope gravity sensitivity (Tg) should be calibrated

max_clones: 11 # how many clones in the sliding window
max_slam: 50 # number of features in our state vector
max_slam_in_update: 25 # update can be split into sequential updates of batches, how many in a batch
max_msckf_in_update: 40 # how many MSCKF features to use in the update
dt_slam_delay: 1 # delay before initializing (helps with stability from bad initialization...)

gravity_mag: 9.81 # magnitude of gravity in this location

feat_rep_msckf: "GLOBAL_3D"
feat_rep_slam: "ANCHORED_MSCKF_INVERSE_DEPTH"
feat_rep_aruco: "ANCHORED_MSCKF_INVERSE_DEPTH"

# zero velocity update parameters we can use
# we support either IMU-based or disparity detection.
try_zupt: true
zupt_chi2_multipler: 0 # set to 0 for only disp-based
zupt_max_velocity: 0.1
zupt_noise_multiplier: 10
zupt_max_disparity: 0.5 # set to 0 for only imu-based
zupt_only_at_beginning: false

# ==================================================================
# ==================================================================

init_window_time: 2.0 # how many seconds to collect initialization information
init_imu_thresh: 2.5 # threshold for variance of the accelerometer to detect a "jerk" in motion
init_max_disparity: 10.0 # max disparity to consider the platform stationary (dependent on resolution)
init_max_features: 50 # how many features to track during initialization (saves on computation)

init_dyn_use: false # if dynamic initialization should be used
init_dyn_mle_opt_calib: false # if we should optimize calibration during intialization (not recommended)
init_dyn_mle_max_iter: 50 # how many iterations the MLE refinement should use (zero to skip the MLE)
init_dyn_mle_max_time: 0.05 # how many seconds the MLE should be completed in
init_dyn_mle_max_threads: 6 # how many threads the MLE should use
init_dyn_num_pose: 6 # number of poses to use within our window time (evenly spaced)
init_dyn_min_deg: 10.0 # orientation change needed to try to init

init_dyn_inflation_ori: 10 # what to inflate the recovered q_GtoI covariance by
init_dyn_inflation_vel: 100 # what to inflate the recovered v_IinG covariance by
init_dyn_inflation_bg: 10 # what to inflate the recovered bias_g covariance by
init_dyn_inflation_ba: 100 # what to inflate the recovered bias_a covariance by
init_dyn_min_rec_cond: 1e-12 # reciprocal condition number thresh for info inversion

init_dyn_bias_g: [ 0.0, 0.0, 0.0 ] # initial gyroscope bias guess
init_dyn_bias_a: [ 0.0, 0.0, 0.0 ] # initial accelerometer bias guess

# ==================================================================
# ==================================================================

record_timing_information: false # if we want to record timing information of the method
record_timing_filepath: "/tmp/traj_timing.txt" # https://docs.openvins.com/eval-timing.html#eval-ov-timing-flame

# if we want to save the simulation state and its diagional covariance
# use this with rosrun ov_eval error_simulation
save_total_state: false
filepath_est: "/tmp/ov_estimate.txt"
filepath_std: "/tmp/ov_estimate_std.txt"
filepath_gt: "/tmp/ov_groundtruth.txt"

# ==================================================================
# ==================================================================

# our front-end feature tracking parameters
# we have a KLT and descriptor based (KLT is better implemented...)
use_klt: true # if true we will use KLT, otherwise use a ORB descriptor + robust matching
num_pts: 200 # number of points (per camera) we will extract and try to track
fast_threshold: 30 # threshold for fast extraction (warning: lower threshs can be expensive)
grid_x: 5 # extraction sub-grid count for horizontal direction (uniform tracking)
grid_y: 5 # extraction sub-grid count for vertical direction (uniform tracking)
min_px_dist: 15 # distance between features (features near each other provide less information)
knn_ratio: 0.70 # descriptor knn threshold for the top two descriptor matches
track_frequency: 31.0 # frequency we will perform feature tracking at (in frames per second / hertz)
downsample_cameras: false # will downsample image in half if true
num_opencv_threads: 4 # -1: auto, 0-1: serial, >1: number of threads
histogram_method: "HISTOGRAM" # NONE, HISTOGRAM, CLAHE

# aruco tag tracker for the system
# DICT_6X6_1000 from https://chev.me/arucogen/
use_aruco: false
num_aruco: 1024
downsize_aruco: true

# ==================================================================
# ==================================================================

# camera noises and chi-squared threshold multipliers
up_msckf_sigma_px: 1
up_msckf_chi2_multipler: 1
up_slam_sigma_px: 1
up_slam_chi2_multipler: 1
up_aruco_sigma_px: 1
up_aruco_chi2_multipler: 1

# masks for our images
use_mask: false

# imu and camera spacial-temporal
# imu config should also have the correct noise values
relative_config_imu: "kalibr_imu_chain.yaml"
relative_config_imucam: "kalibr_imucam_chain.yaml"
```
