### ISSUE TITLE
🚀 Sending time/velocity with the trajectory

### ISSUE THREAD

**Issue by lidiaxp** [ctu-mrs/mrs_uav_system#193]
I’m looking to implement a system that allows a UAV to follow a predefined trajectory, including both position and time/velocity. I’ve found two possible approaches within the system:

1. Using the topic `/control_manager/trajectory_reference`, which accepts a message with the following structure:
```
trajectory:
  header:
    seq: 0
    stamp: {secs: 0, nsecs: 0}
    frame_id: ''
  input_id: 0
  use_heading: false
  fly_now: false
  loop: false
  dt: 0.0
  points:
  - position: {x: 0.0, y: 0.0, z: 0.0}
    heading: 0.0
```

2. Using the topic `/trajectory_generation/path`, which accepts a message with the following structure:
```
path:
  header:
    seq: 0
    stamp: {secs: 0, nsecs: 0}
    frame_id: ''
  input_id: 0
  use_heading: false
  fly_now: false
  stop_at_waypoints: false
  loop: false
  max_execution_time: 0.0
  max_deviation_from_path: 0.0
  dont_prepend_current_state: false
  override_constraints: false
  override_max_velocity_horizontal: 0.0
  override_max_acceleration_horizontal: 0.0
  override_max_jerk_horizontal: 0.0
  override_max_velocity_vertical: 0.0
  override_max_acceleration_vertical: 0.0
  override_max_jerk_vertical: 0.0
  relax_heading: false
  points:
  - position: {x: 0.0, y: 0.0, z: 0.0}
    heading: 0.0
```

In both cases, I’ve only been able to send positional data. How can I include velocity or timing information for each waypoint in the trajectory? Any advice or suggestions would be greatly appreciated!
